"""
Pydantic models defining the complete JSON structure for a generated site.

Flat schema — each content block is a top-level key.
If a block is None/null, that section and its corresponding page are disabled.
Navigation and footer are auto-generated from the data by the viewer.

THIS FILE IS THE SOURCE OF TRUTH FOR THE SITE SCHEMA.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
BACKWARD COMPATIBILITY RULES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

After production launch, existing customer sites depend on this schema.
Breaking changes will corrupt live sites. Follow these rules:

  1. NEW FIELDS MUST BE OPTIONAL with sensible defaults.
     Example:  badge: str = ""           # OK — old sites get empty string
     Bad:      badge: str                 # BREAKS — old sites have no value

  2. NEVER REMOVE a field. If deprecated, keep it with a default and ignore
     it in new viewer versions.

  3. NEVER RENAME a field. Add the new name as an alias or new field instead.

  4. NEVER CHANGE A FIELD'S TYPE. If you need a different type, add a new
     field (e.g. cta_v2) and let the viewer prefer the new one.

  5. NEW SECTIONS follow the same rule: optional with None default.
     Example:  pricing: PricingData | None = None

  6. VIEWER VERSION: Each site has a `viewer_version` field that locks it to
     a specific set of viewer components. New viewer features should target
     the latest version only. Old versions ignore unknown fields.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

When adding, removing, or changing a section/field, update ALL of the following:

  Backend (this project):
    [x] backend/app/sites/site_schema.py        — Pydantic models (you are here)
    [ ] backend/app/ai/generator.py             — _VALID_TOP_LEVEL_KEYS (if new top-level key)

  Frontend (dashboard editor):
    [ ] frontend/.../pages/[id]/page.tsx         — SiteData interface, DEFAULT_SECTION_ORDER, SECTION_MAP
    [ ] frontend/.../pages/[id]/code/page.tsx    — VALID_SECTION_KEYS, SECTION_RULES, SECTION_FILES
    [ ] frontend/.../pages/[id]/settings/page.tsx — SiteData interface (only if meta/business/seo changed)

  Viewer (public site renderer):
    [ ] viewer/lib/types.ts                      — SiteData TypeScript interface
    [ ] viewer/lib/version-registry.ts           — Register section in version renderer(s)
    [ ] viewer/components/live-preview-wrapper.tsx — DEFAULT_ORDER, renderSection()
    [ ] viewer/components/preview-shell.tsx       — DEFAULT_ORDER, renderSection()
    [ ] viewer/lib/sanitize.ts                   — arrayFields (if new section has a list field)
    [ ] viewer/lib/navigation.ts                 — buildNavigation() (if section should appear in nav)
"""

from __future__ import annotations

from pydantic import BaseModel, Field

# The viewer version assigned to newly generated sites.
# Bump this when you release a new viewer design version (v2, v3, ...).
# Existing sites keep whatever version they were created with.
CURRENT_VIEWER_VERSION = "v1"


# ---------------------------------------------------------------------------
# Building blocks
# ---------------------------------------------------------------------------

class CTAButton(BaseModel):
    label: str
    href: str


class Colors(BaseModel):
    primary: str = "#2563eb"
    secondary: str = "#1e40af"
    accent: str = "#f59e0b"
    background: str = "#ffffff"
    text: str = "#111827"


class Fonts(BaseModel):
    heading: str = "Inter"
    body: str = "Inter"


class Branding(BaseModel):
    logo_url: str | None = None
    colors: Colors = Colors()
    fonts: Fonts = Fonts()


class MetaInfo(BaseModel):
    title: str = ""
    description: str = ""
    keywords: list[str] = []
    og_image: str | None = None
    favicon_url: str | None = None
    language: str = "sv"


class BusinessInfo(BaseModel):
    name: str = ""
    tagline: str = ""
    email: str | None = None
    phone: str | None = None
    address: str | None = None
    org_number: str | None = None
    social_links: dict[str, str] = {}


class SEOConfig(BaseModel):
    structured_data: dict = {}
    robots: str = "index, follow"


# ---------------------------------------------------------------------------
# Content blocks (each is optional — null = section/page OFF)
# ---------------------------------------------------------------------------

class HeroData(BaseModel):
    headline: str
    subtitle: str = ""
    cta: CTAButton | None = None
    background_image: str | None = None
    # Editor-only config (not generated by AI — defaults are fine)
    show_cta: bool = True


class Highlight(BaseModel):
    label: str
    value: str


class AboutData(BaseModel):
    title: str = "Om oss"
    text: str = ""
    image: str | None = None
    highlights: list[Highlight] | None = None
    show_highlights: bool = True


class ServiceItem(BaseModel):
    title: str
    description: str


class ServicesData(BaseModel):
    title: str = "Våra tjänster"
    subtitle: str = ""
    items: list[ServiceItem] = []


class GalleryImage(BaseModel):
    url: str
    alt: str = ""
    caption: str = ""


class GalleryData(BaseModel):
    title: str = "Galleri"
    subtitle: str = ""
    images: list[GalleryImage] = []


class TestimonialItem(BaseModel):
    text: str
    author: str
    role: str = ""


class TestimonialsData(BaseModel):
    title: str = "Omdömen"
    subtitle: str = ""
    items: list[TestimonialItem] = []
    show_ratings: bool = True


class CTAData(BaseModel):
    title: str
    text: str = ""
    button: CTAButton | None = None
    show_button: bool = True


class ContactData(BaseModel):
    title: str = "Kontakta oss"
    text: str = ""
    show_form: bool = True
    show_info: bool = True


# ---------------------------------------------------------------------------
# NEW: Extended content blocks
# ---------------------------------------------------------------------------

class FeatureItem(BaseModel):
    title: str
    description: str
    icon: str = ""  # emoji or icon name


class FeaturesData(BaseModel):
    title: str = "Varför välja oss"
    subtitle: str = ""
    items: list[FeatureItem] = []


class StatItem(BaseModel):
    value: str  # e.g. "500+", "25 år", "98%"
    label: str  # e.g. "Nöjda kunder", "Erfarenhet", "Kundnöjdhet"


class StatsData(BaseModel):
    title: str = ""
    items: list[StatItem] = []


class TeamMember(BaseModel):
    name: str
    role: str = ""
    image: str | None = None
    bio: str = ""


class TeamData(BaseModel):
    title: str = "Vårt team"
    subtitle: str = ""
    members: list[TeamMember] = []


class FAQItem(BaseModel):
    question: str
    answer: str


class FAQData(BaseModel):
    title: str = "Vanliga frågor"
    subtitle: str = ""
    items: list[FAQItem] = []


class ProcessStep(BaseModel):
    title: str
    description: str
    step_number: int = 0


class ProcessData(BaseModel):
    title: str = "Så fungerar det"
    subtitle: str = ""
    steps: list[ProcessStep] = []


# ---------------------------------------------------------------------------
# Full site schema
# ---------------------------------------------------------------------------

class SiteSchema(BaseModel):
    """
    The complete JSON schema for a generated site.
    Stored in GeneratedSite.site_data.
    """
    meta: MetaInfo = MetaInfo()
    theme: str = "modern"
    branding: Branding = Branding()
    business: BusinessInfo = BusinessInfo()

    # Viewer version — locks this site to a specific set of viewer components.
    # Set automatically on generation from CURRENT_VIEWER_VERSION.
    # Existing sites without this field default to "v1".
    viewer_version: str = CURRENT_VIEWER_VERSION

    # Section display order — list of section keys in desired render order.
    # When absent, the viewer uses the default order.
    section_order: list[str] = Field(
        default_factory=lambda: [
            "hero", "about", "features", "stats", "services", "process",
            "gallery", "team", "testimonials", "faq", "cta", "contact",
        ]
    )

    # Style variant — randomly assigned after AI generation to give visual variety.
    # All sections on the page share the same variant number.
    # 0 = Original, 1 = Modern Cards, 2 = Clean & Minimal, 3 = Bold & Filled
    style_variant: int = 0

    # Content blocks — null means OFF
    hero: HeroData | None = None
    about: AboutData | None = None
    features: FeaturesData | None = None
    stats: StatsData | None = None
    services: ServicesData | None = None
    process: ProcessData | None = None
    gallery: GalleryData | None = None
    team: TeamData | None = None
    testimonials: TestimonialsData | None = None
    faq: FAQData | None = None
    cta: CTAData | None = None
    contact: ContactData | None = None

    seo: SEOConfig = SEOConfig()
