"""
Prompt templates for AI site generation.

Flat schema — the AI fills top-level content blocks.
Navigation, footer, and page structure are auto-generated by the viewer.
"""

from __future__ import annotations

# Fallback industry hints used when no DB prompt_hint exists.
# Kept for backward compatibility with the old hardcoded approach.
INDUSTRY_HINTS: dict[str, str] = {
    "bygg": "Fokusera på pålitlighet, erfarenhet och kvalitet. Använd starka CTA:er som 'Begär offert'. Visa upp projekt/referenser. Lyft fram certifieringar.",
    "restaurang": "Framhäv meny, atmosfär och läge. Inkludera öppettider och boknings-CTA. Visa matbilder i galleriet.",
    "frisör": "Visa upp tjänster med priser. Boka-tid-CTA. Lyxig känsla. Visa före/efter-bilder.",
    "tandvård": "Professionellt och tryggt. Framhäv behandlingar och personal. Boka-tid-CTA. Teamsektion med tandläkare.",
    "redovisning": "Seriöst och kompetent. Framhäv tjänster, erfarenhet och kundrelationer. Processektion.",
    "städ": "Pålitlighet och flexibilitet. Visa tjänster, priser och kundomdömen. Processektion.",
    "el": "Certifiering och säkerhet. Visa tjänster och tillgänglighet. Akut-CTA. Lyft auktoriserad elektriker.",
    "elektriker": "Certifiering och säkerhet. Visa tjänster och tillgänglighet. Akut-CTA. Lyft auktoriserad elektriker.",
    "vvs": "Snabb service och pålitlighet. Jour-CTA. Visa tjänster tydligt. Processektion.",
    "skönhet": "Lyxig och elegant känsla. Visa produkter/behandlingar i galleri. Boka-tid-CTA.",
    "fitness": "Energisk och motiverande. Visa träningsformer, schema och priser. Boka-provpass-CTA.",
    "juridik": "Professionellt och tryggt. Framhäv expertområden och erfarenhet. Boka-konsultation-CTA.",
    "it": "Modern och teknisk. Visa tjänster, teknikstack och case studies. Boka-demo-CTA.",
}

# Default prompt hint for industries not in the DB
DEFAULT_INDUSTRY_HINT = (
    "Skapa en professionell och engagerande sida som passar branschen. "
    "Använd en tydlig CTA som 'Kontakta oss'. Framhäv tjänster, erfarenhet och kundnöjdhet."
)

SYSTEM_PROMPT = """Du är en expert webbdesigner som skapar moderna, vackra hemsidor för svenska småföretag.

Du får scrapad data och screenshots från ett företags befintliga hemsida. Du ska generera ett KOMPLETT och RIKT JSON-schema för en ny, professionell hemsida.

REGLER:
1. Svara ENBART med valid JSON som matchar det angivna schemat. Ingen annan text.
2. Alla texter ska vara på svenska om inte originalet är på engelska.
3. Skriv KORTFATTAT och SLAGKRAFTIGT — varje mening ska ha ett syfte. Undvik upprepningar och utfyllnadstext. About-text: 80-120 ord. Beskrivningar: max 2 meningar.
4. FÄRGER: Använd de EXAKTA färgerna från den visuella analysen. Om visuell analys saknas, använd CSS-färgerna. Förbättra bara om färgerna är genuint dåliga.
5. Varje content-block (hero, about, services, etc.) är en separat nyckel. Sätt till null om sektionen inte är relevant.
6. Inkludera INTE navigation eller footer — det genereras automatiskt.
7. VIKTIGT — VÄLJ SEKTIONER INTELLIGENT baserat på företagets storlek, bransch och tillgänglig information:
   - En enkel affärsidé behöver FÄRRE sektioner (3-5). T.ex. hero + about + contact räcker för en frisör.
   - Ett större företag med mycket information kan ha fler sektioner (5-8).
   - Inkludera ALDRIG alla sektioner. Välj de mest relevanta.
   - "hero" ska ALLTID inkluderas.
   - Sektioner som pricing, team, ranking, video, logo_cloud ska BARA inkluderas om det finns relevant data eller det verkligen passar branschen.
   - Tomma/generiska sektioner är värre än inga sektioner alls.
7b. Inkludera en "section_order"-nyckel med ENBART de sektioner du valt, i optimal visningsordning. Anpassa ordningen efter bransch.
8. CTA-KNAPPAR & LÄNKAR — VIKTIGT:
   - Bestäm FÖRST vilka pages du ska skapa (slug-lista). Sedan använd de slugsen som href i knappar.
   - Om du skapar en kontaktsida med slug "kontakt" → alla CTA-knappar ska peka till "/kontakt" (INTE "#contact").
   - Om du skapar en tjänstesida med slug "tjanster" → "Se våra tjänster"-knappar ska peka till "/tjanster".
   - Alla href i CTA-knappar MÅSTE matcha en faktisk page-slug eller vara en extern URL.
   - Använd ALDRIG "#contact" eller andra ankarlänkar. Använd alltid riktiga sidreferenser som "/kontakt".
   - Kontrollera att VARJE href i hela JSON:en pekar till en sida som faktiskt finns i pages-arrayen.
9. Generera 4-6 services om företaget har tjänster.
10. Generera 3-5 features/fördelar.
11. Generera 3-4 stats/nyckeltal med realistiska värden.
12. Generera 4-6 FAQ-frågor relevanta för branschen.
13. Generera 3-4 steg i en process-sektion om relevant.
14. Generera 2-3 testimonials med realistiska svenska namn.
15. SEO: Generera BARA title och description i meta. Skippa structured_data och robots — det genereras automatiskt senare.
16. Använd BARA bild-URL:er som finns i listan med tillgängliga bilder. Hitta INTE PÅ nya URL:er.
17. STYLE VARIANT: Sidan tilldelas automatiskt en slumpmässig visuell stilvariant (style_variant) EFTER din generering — du behöver INTE ange den.

SECTION_SETTINGS — per-sektion animation:
Inkludera "section_settings" i din JSON. Variera animationer mellan sektioner.
Tillgängliga animationer: "fade-up", "fade-in", "slide-left", "slide-right", "scale", "none".
Exempel:
"section_settings": {
  "hero": {"animation": "fade-in"},
  "about": {"animation": "slide-right"},
  "features": {"animation": "fade-up"},
  "stats": {"animation": "scale"},
  "services": {"animation": "slide-left"}
}
Regel: Hero bör använda "fade-in" eller "none". Variera övriga sektioner — använd INTE samma animation överallt.

NYA SEKTIONSTYPER (använd när det är relevant):
- "pricing": Pristabell med tiers. Varje tier har name, price, description, features[], highlighted, cta.
- "video": YouTube/Vimeo-video med title och video_url.
- "logo_cloud": Partners/kunder med logotyper. Varje logo har name och image_url.
- "custom_content": Fritext-sektion med blocks[]. Varje block har type ("text"/"image"/"button"/"heading"), content, url, alt, label, href.
- "banner": Fullbredd-meddelande med text och valfri button.
- "ranking": Topplista / bäst-i-test-sektion med rankade objekt. Perfekt för jämförelsesidor, topp-5/10-listor, produktrecensioner. Varje item har rank (nummer), title, description, image (URL eller null), link ({label, href} eller null för extern länk/knapp).

AUTO-INSTALL APPAR:
Om kunden uttryckligen nämner att de vill ha en blogg, nyheter eller artiklar, inkludera:
  "install_apps": ["blog"]
Om kunden nämner chatt, kundtjänst eller livechatt, inkludera:
  "install_apps": ["chat"]
Tillgängliga appar: "blog", "chat". Inkludera BARA om det finns tydlig anledning från kundens beskrivning.
Om ingen app behövs, utelämna install_apps eller sätt till tom lista.

MULTI-PAGE CRAWL-DATA:
Du kan få en sektion med "MULTI-PAGE CRAWL" som innehåller data från flera undersidor på den befintliga sajten.
Använd denna information intelligent:
- Om en blogg/nyhetssida hittades → inkludera "blog" i install_apps.
- Om en bokningssida hittades → se till att CTA:er fokuserar på bokning.
- Om en prissida hittades → inkludera pricing-sektionen.
- Om portfolio/referenssida hittades → inkludera gallery med de bilderna.
- Innehåll från undersidor (om-oss, tjänster, FAQ, team) har redan berikats i scrapad data ovan.
- Använd GENERERINGSNOTERNA aktivt — de är specifika rekommendationer baserade på crawl-analysen.
- Bilder med source_page-kontext visar var bilderna användes på den gamla sajten — placera dem smart.

FLERSIDIGT STÖD (pages):
Startsidan byggs av de vanliga top-level sektionerna (hero, about, services, etc.).
Utöver startsidan kan du skapa SEPARATA undersidor via "pages"-arrayen.

REGLER FÖR PAGES:
- Skapa 2-4 undersidor MAX. Inte fler.
- Varje sida har: slug, title, meta (SEO), sections (lista av sektionstyper med data).
- Sektionerna i pages använder SAMMA typer som startsidan: "hero", "about", "services", "features", "faq", "contact", "pricing", "gallery", "process", "testimonials", "cta", "custom_content", "stats", "team", "banner", "video".
- Varje page-sektion har: type (sektionstyp) och data (matchande fält för den typen).
- parent_slug: sätt till null för toppnivå-sidor. Använd parent_slug för child-sidor (t.ex. parent_slug="tjanster" för en undersida till /tjanster/).
- show_in_nav: true om sidan ska visas i navigationen, false om den är en child-sida eller dold.
- nav_order: ordning i navigationen (lägre = först).

NÄR SKA DU SKAPA PAGES:
- Enkel affärsidé (frisör, bilrekond): 2-3 sidor. T.ex. startsida + "Om oss" + "Boka tid".
- Tjänsteföretag: 2-4 sidor. T.ex. startsida + "Tjänster" + "Om oss" + "Kontakt".
- Om det finns mycket innehåll som inte passar på startsidan, bryt ut det till egna sidor.
- Startsidans sektioner ska vara KORTA snippets/sammanfattningar. De fullständiga versionerna läggs på undersidor.
- Sätt INTE samma fullständiga innehåll på både startsidan och en undersida.

STRATEGI:
1. Startsidan: hero + korta snippets (about-snippet, services-snippet, testimonials, CTA).
2. Undersidor: fullständiga versioner av about, services, FAQ, kontakt, etc.
3. Om startsidan har en about-snippet → skapa en /om-oss sida med utförligare about + features/stats.
4. Om startsidan har services-snippet → skapa en /tjanster sida med alla tjänster i detalj.
5. Kontaktsida är nästan alltid relevant som egen sida.

TILLGÄNGLIGA STILVARIANTER:
─────────────────────────────
Variant 0 — Original:
  Rundade kort (rounded-2xl), centrerade rubriker, gradient-blobbar, vertikal timeline, accordion-FAQ.

Variant 1 — Modern Cards:
  Mjuka skuggor (rounded-xl), kort-baserad process, citat-stil testimonials, featured galleri.

Variant 2 — Clean & Minimal:
  Vänsterjusterade rubriker, inga blobbar, liten radius, FAQ i två kolumner, split CTA.

Variant 3 — Bold & Filled:
  Inga borders, stora skuggor (shadow-lg), pill-knappar, masonry-galleri, glasmorfism-CTA.
─────────────────────────────"""

USER_PROMPT_TEMPLATE = """Skapa en komplett hemsida i JSON-format för detta företag.

═══════════════════════════════════════
FÖRETAGSINFO
══════════���════════════════════════��═══
Namn: {business_name}
Bransch: {industry}
Hemsida: {website_url}

KONTAKTUPPGIFTER:
Email: {email}
Telefon: {phone}
Adress: {address}
Sociala medier: {social_links}

═══════════════════════════════════════
SCRAPAD DATA FRÅN BEFINTLIG HEMSIDA
══════════════���════════════════════════

SIDTITEL: {page_title}

HERO-RUBRIK: {hero_text}
HERO-UNDERTEXT: {hero_subtitle}

META-BESKRIVNING: {meta_description}

OM OSS-TEXT:
{about_text}

ALLA RUBRIKER PÅ SIDAN:
{headings_summary}

ALLA TEXTER/STYCKEN:
{paragraphs_summary}

TJÄNSTER HITTADE:
{services_summary}

FEATURES/FÖRDELAR HITTADE:
{features_summary}

FAQ HITTADE:
{faq_summary}

TEAMMEDLEMMAR HITTADE:
{team_summary}

═══════════���═══════════════════════════
FÄRGER
═════���═════════════════════════════════
CSS-extraherade färger: {css_colors}

{visual_colors_section}

INSTRUKTION: Om visuella färger finns ovan, ANVÄND DEM — de är exakta hex-koder från screenshots.
Om de saknas, använd CSS-färgerna som grund.

═══════════════════════════════════════
BILDER (använd ENBART dessa URL:er)
══════════════════��════════════════════
{images_summary}

═══════════════════════════════════════
VISUELL ANALYS AV BEFINTLIG HEMSIDA
════════���══════════════════════════════
{visual_analysis_summary}

{crawl_report_section}

{industry_hint}

{recommended_sections}

═════��═════════════════════════════════
JSON-SCHEMA ATT FYLLA I
═══════��═══════════════════════════════

VIKTIGT:
- Svara med ENBART valid JSON
- Använd de tillhandahållna bild-URL:erna. Hitta INTE PÅ nya.
- Inkludera INTE "navigation" eller "footer" — det genereras automatiskt
- Skriv KORTFATTAT — about max 120 ord, beskrivningar max 2 meningar
- Inkludera "section_settings" med varierade animationer per sektion
- Inkludera BARA sektioner som är relevanta — välj INTELLIGENT baserat på kontext
- Sektioner du INTE inkluderar ska sättas till null eller utelämnas helt
- Inkludera "ranking" om sidan handlar om jämförelser/toplistor/bäst-i-test
- Inkludera "pages" med 2-4 undersidor. Startsidan = snippets, undersidor = fullständigt innehåll

{{
  "meta": {{
    "title": "Företagsnamn | Kort beskrivning",
    "description": "150-160 tecken lång SEO-beskrivning",
    "keywords": ["nyckelord1", "nyckelord2"],
    "language": "sv"
  }},
  "theme": "modern",
  "branding": {{
    "logo_url": "{logo_url}",
    "colors": {{
      "primary": "#hex",
      "secondary": "#hex",
      "accent": "#hex",
      "background": "#hex",
      "text": "#hex"
    }},
    "fonts": {{ "heading": "Inter", "body": "Inter" }}
  }},
  "business": {{
    "name": "", "tagline": "Kort slogan 5-8 ord",
    "email": "", "phone": "", "address": "",
    "org_number": null,
    "social_links": {{}}
  }},
  "section_order": ["hero", "about", "services", "..."],
  "section_settings": {{
    "hero": {{"animation": "fade-in"}},
    "about": {{"animation": "slide-right"}},
    "services": {{"animation": "fade-up"}}
  }},
  "hero": {{
    "headline": "Kraftfull rubrik, max 8 ord",
    "subtitle": "1-2 meningar som förklarar vad företaget gör",
    "cta": {{ "label": "Tydlig CTA-text", "href": "/kontakt" }},
    "background_image": null
  }},
  "about": {{
    "title": "Om oss",
    "text": "80-120 ord om företaget.",
    "image": null,
    "highlights": [
      {{ "label": "Beskrivning", "value": "Nyckeltal" }}
    ]
  }},
  "features": {{
    "title": "Varför välja oss",
    "subtitle": "Kort beskrivning",
    "items": [
      {{ "title": "Fördel", "description": "Max 2 meningar" }}
    ]
  }},
  "stats": {{
    "title": "",
    "items": [
      {{ "value": "500+", "label": "Nöjda kunder" }}
    ]
  }},
  "services": {{
    "title": "Våra tjänster",
    "subtitle": "Kort intro",
    "items": [
      {{ "title": "Tjänst", "description": "Max 2 meningar" }}
    ]
  }},
  "process": {{
    "title": "Så fungerar det",
    "subtitle": "",
    "steps": [
      {{ "title": "Steg 1", "description": "Kort beskrivning", "step_number": 1 }}
    ]
  }},
  "gallery": {{
    "title": "Våra projekt",
    "subtitle": "",
    "images": [
      {{ "url": "bild-url-från-listan", "alt": "Alt-text", "caption": "" }}
    ]
  }},
  "team": {{
    "title": "Möt teamet",
    "subtitle": "",
    "members": [
      {{ "name": "Namn", "role": "Roll", "image": null, "bio": "1 mening" }}
    ]
  }},
  "testimonials": {{
    "title": "Vad våra kunder säger",
    "subtitle": "",
    "items": [
      {{ "text": "2-3 meningar recension", "author": "Svenskt namn", "role": "Kund" }}
    ]
  }},
  "faq": {{
    "title": "Vanliga frågor",
    "subtitle": "",
    "items": [
      {{ "question": "Fråga?", "answer": "1-2 meningar svar" }}
    ]
  }},
  "cta": {{
    "title": "Redo att komma igång?",
    "text": "1 mening",
    "button": {{ "label": "CTA-text", "href": "/kontakt" }}
  }},
  "contact": {{
    "title": "Kontakta oss",
    "text": "1 mening"
  }},
  "pricing": null,
  "video": null,
  "logo_cloud": null,
  "custom_content": null,
  "banner": null,
  "ranking": {{
    "title": "Topp 5 bästa ...",
    "subtitle": "Kort intro",
    "items": [
      {{ "rank": 1, "title": "Namn", "description": "Kort beskrivning", "image": null, "link": {{ "label": "Besök", "href": "https://..." }} }}
    ]
  }},
  "pages": [
    {{
      "slug": "om-oss",
      "title": "Om oss",
      "meta": {{ "title": "Om oss | Företagsnamn", "description": "Läs mer om oss." }},
      "sections": [
        {{ "type": "about", "data": {{ "title": "Om oss", "text": "Fullständig om oss-text, 80-120 ord." }} }},
        {{ "type": "stats", "data": {{ "title": "", "items": [{{ "value": "10+", "label": "År i branschen" }}] }} }}
      ],
      "parent_slug": null,
      "show_in_nav": true,
      "nav_order": 1
    }},
    {{
      "slug": "kontakt",
      "title": "Kontakta oss",
      "meta": {{ "title": "Kontakt | Företagsnamn", "description": "Kontakta oss." }},
      "sections": [
        {{ "type": "contact", "data": {{ "title": "Kontakta oss", "text": "Vi svarar inom 24h." }} }}
      ],
      "parent_slug": null,
      "show_in_nav": true,
      "nav_order": 10
    }}
  ],
  "seo": {{
    "structured_data": {{}},
    "robots": "index, follow"
  }},
  "install_apps": []
}}"""


def _sanitize_for_prompt(text: str, max_length: int = 500) -> str:
    """Sanitize user input before inserting into LLM prompts."""
    if not text:
        return ""
    text = text.replace("```", "")
    text = text.replace("SYSTEM:", "")
    text = text.replace("ASSISTANT:", "")
    text = text.replace("USER:", "")
    text = text.replace("HUMAN:", "")
    return text[:max_length].strip()


def build_prompt(
    business_name: str,
    industry: str | None,
    website_url: str,
    email: str | None,
    phone: str | None,
    address: str | None,
    texts: dict | None,
    colors: dict | None,
    services: list | None,
    logo_url: str | None,
    social_links: dict | None,
    images: list | None = None,
    visual_analysis: dict | None = None,
    industry_prompt_hint: str | None = None,
    industry_default_sections: list[str] | None = None,
    crawl_report: dict | None = None,
) -> tuple[str, str]:
    """Build (system_prompt, user_prompt) pair."""

    # --- Texts ---
    page_title = ""
    hero_text = ""
    hero_subtitle = ""
    meta_description = ""
    about_text = "Ingen about-text hittad."
    headings_summary = "Inga rubriker hittade."
    paragraphs_summary = "Inga texter hittade."
    features_summary = "Inga features hittade."
    faq_summary = "Ingen FAQ hittad."
    team_summary = "Inga teammedlemmar hittade."

    if texts:
        if texts.get("title"):
            page_title = _sanitize_for_prompt(texts["title"], 300)
        if texts.get("hero_text"):
            hero_text = _sanitize_for_prompt(texts["hero_text"], 300)
        if texts.get("hero_subtitle"):
            hero_subtitle = _sanitize_for_prompt(texts["hero_subtitle"], 500)
        if texts.get("description"):
            meta_description = _sanitize_for_prompt(texts["description"], 500)
        if texts.get("about"):
            about_text = _sanitize_for_prompt(texts["about"], 2000)

        # All headings
        if texts.get("headings"):
            h_parts = []
            for h in texts["headings"][:20]:
                h_parts.append(f"[{h['level']}] {_sanitize_for_prompt(h['text'], 200)}")
            if h_parts:
                headings_summary = "\n".join(h_parts)

        # All paragraphs — send much more text to the AI
        if texts.get("paragraphs"):
            p_parts = []
            for p in texts["paragraphs"][:20]:
                p_parts.append(f"- {_sanitize_for_prompt(p, 500)}")
            if p_parts:
                paragraphs_summary = "\n".join(p_parts)

        # Features
        if texts.get("features"):
            f_parts = []
            for f in texts["features"][:8]:
                title = _sanitize_for_prompt(f.get("title", ""), 150)
                desc = _sanitize_for_prompt(f.get("description", ""), 300)
                f_parts.append(f"- {title}: {desc}" if desc else f"- {title}")
            if f_parts:
                features_summary = "\n".join(f_parts)

        # FAQ
        if texts.get("faq_items"):
            faq_parts = []
            for fq in texts["faq_items"][:10]:
                q = _sanitize_for_prompt(fq.get("question", ""), 200)
                a = _sanitize_for_prompt(fq.get("answer", ""), 500)
                faq_parts.append(f"Q: {q}\nA: {a}")
            if faq_parts:
                faq_summary = "\n".join(faq_parts)

        # Team
        if texts.get("team_members"):
            tm_parts = []
            for tm in texts["team_members"][:8]:
                name = _sanitize_for_prompt(tm.get("name", ""), 100)
                role = _sanitize_for_prompt(tm.get("role", ""), 100)
                tm_parts.append(f"- {name} ({role})" if role else f"- {name}")
            if tm_parts:
                team_summary = "\n".join(tm_parts)

    # --- Services ---
    services_summary = "Inga tjänster hittade."
    if services:
        svc_list = []
        for s in services[:12]:
            title = _sanitize_for_prompt(s.get("title", ""), 150)
            desc = _sanitize_for_prompt(s.get("description", ""), 300)
            svc_list.append(f"- {title}: {desc}" if desc else f"- {title}")
        services_summary = "\n".join(svc_list)

    # --- Industry hint ---
    # Priority: 1) DB prompt_hint  2) hardcoded INDUSTRY_HINTS  3) DEFAULT_INDUSTRY_HINT
    industry_hint = ""
    if industry_prompt_hint:
        industry_hint = (
            f"\n════════��══════════════════════════════\n"
            f"BRANSCH-TIPS (specifikt för denna bransch):\n"
            f"{industry_prompt_hint}\n"
            f"════════════════���══════════════════════"
        )
    elif industry and industry.lower() in INDUSTRY_HINTS:
        industry_hint = (
            f"\n═══════���═══════════════════════════════\n"
            f"BRANSCH-TIPS: {INDUSTRY_HINTS[industry.lower()]}\n"
            f"════════════���══════════════════════════"
        )

    # --- Recommended sections from industry ---
    recommended_sections = ""
    if industry_default_sections:
        sections_str = ", ".join(f'"{s}"' for s in industry_default_sections)
        recommended_sections = (
            f"\n═══════════════════���═══════════════════\n"
            f"REKOMMENDERADE SEKTIONER FÖR DENNA BRANSCH:\n"
            f"Använd denna ordning som utgångspunkt för section_order: [{sections_str}]\n"
            f"Du kan anpassa om det passar bättre, men inkludera minst dessa sektioner.\n"
            f"═══════════════════════════════════════"
        )

    # --- Colors ---
    css_colors = "Inga färger"
    if colors:
        css_colors = f"Primary: {colors.get('primary', '?')}, Secondary: {colors.get('secondary', '?')}, Accent: {colors.get('accent', '?')}"

    # Visual colors (from vision analysis — these are the REAL colors)
    visual_colors_section = ""
    if visual_analysis and isinstance(visual_analysis.get("colors"), dict):
        vc = visual_analysis["colors"]
        parts = ["VISUELLA FÄRGER (exakta hex-koder från screenshots — ANVÄND DESSA):"]
        for key in ["primary", "secondary", "accent", "background", "text"]:
            if vc.get(key):
                parts.append(f"  {key}: {vc[key]}")
        visual_colors_section = "\n".join(parts)

    # --- Images ---
    images_summary = "Inga bilder tillgängliga."
    if images:
        img_parts = []
        for img in images[:20]:
            if isinstance(img, str):
                # Plain URL or data-URI from frontend upload
                if img:
                    img_parts.append(f"- [user-upload] {img[:120]}")
            elif isinstance(img, dict):
                url = img.get("url", "")
                alt = img.get("alt", "")
                cat = img.get("category", "general")
                w = img.get("width", "?")
                h = img.get("height", "?")
                if url:
                    line = f"- [{cat}] {url}"
                    if alt:
                        line += f" (alt: {alt})"
                    if w != "?" and h != "?":
                        line += f" [{w}x{h}]"
                    # Include source page context if from subpage crawl
                    src_page = img.get("source_page")
                    ctx_heading = img.get("context_heading")
                    if src_page:
                        line += f" [från: {src_page}]"
                    if ctx_heading:
                        line += f" [sektion: {ctx_heading[:60]}]"
                    img_parts.append(line)
        if img_parts:
            images_summary = "\n".join(img_parts)

    # --- Visual analysis summary ---
    visual_analysis_summary = "Ingen visuell analys tillgänglig."
    if visual_analysis:
        va_parts = []

        if visual_analysis.get("design_style"):
            va_parts.append(f"Designstil: {visual_analysis['design_style']}")
        if visual_analysis.get("mood"):
            va_parts.append(f"Känsla/stämning: {visual_analysis['mood']}")
        if visual_analysis.get("overall_quality"):
            va_parts.append(f"Kvalitetsnivå: {visual_analysis['overall_quality']}")

        if visual_analysis.get("typography"):
            typo = visual_analysis["typography"]
            va_parts.append(f"Typografi: {typo.get('heading_style', '?')} rubriker, {typo.get('body_style', '?')} brödtext, vikt: {typo.get('heading_weight', '?')}")

        if visual_analysis.get("layout"):
            layout = visual_analysis["layout"]
            va_parts.append(f"Layout: hero={layout.get('hero_type', '?')}, sektioner={layout.get('section_count', '?')}")

        if visual_analysis.get("content_sections"):
            va_parts.append("Identifierade sektioner:")
            for sec in visual_analysis["content_sections"][:10]:
                sec_type = sec.get("type", "?")
                headline = sec.get("headline", "")
                summary = sec.get("summary", "")
                va_parts.append(f"  - [{sec_type}] {headline}: {summary}" if headline else f"  - [{sec_type}] {summary}")

        if visual_analysis.get("cta_buttons"):
            va_parts.append(f"CTA-knappar: {', '.join(visual_analysis['cta_buttons'][:5])}")

        if visual_analysis.get("business_info_visible"):
            biz = visual_analysis["business_info_visible"]
            for key in ["name", "tagline", "phone", "email"]:
                if biz.get(key):
                    va_parts.append(f"Synlig {key}: {biz[key]}")

        if visual_analysis.get("images"):
            img_info = visual_analysis["images"]
            va_parts.append(f"Bilder: {img_info.get('total_visible', '?')} synliga, stil={img_info.get('image_style', '?')}, kvalitet={img_info.get('image_quality', '?')}")

        if visual_analysis.get("improvement_areas"):
            areas = visual_analysis["improvement_areas"]
            if isinstance(areas, list):
                va_parts.append(f"Förbättringsområden: {', '.join(areas[:4])}")
            else:
                va_parts.append(f"Förbättringsomr��den: {areas}")

        if va_parts:
            visual_analysis_summary = "\n".join(va_parts)

    # --- Crawl report (multi-page data) ---
    crawl_report_section = ""
    if crawl_report:
        cr_parts = []

        # Site map
        site_map = crawl_report.get("site_map", [])
        if site_map:
            cr_parts.append("SIDKARTA (hittade undersidor):")
            for page in site_map:
                label = page.get("nav_label", "?")
                ptype = page.get("page_type", "other")
                path = page.get("path", "?")
                img_count = page.get("image_count", 0)
                content_summary = page.get("content_summary")
                cr_parts.append(f"  - [{ptype}] {label} ({path}) — {img_count} bilder")

                # Include key content from subpages
                if content_summary:
                    if content_summary.get("about"):
                        cr_parts.append(f"    Om-text: {_sanitize_for_prompt(content_summary['about'], 300)}")
                    if content_summary.get("services"):
                        svc_titles = [s.get("title", "") for s in content_summary["services"][:6]]
                        cr_parts.append(f"    Tjänster: {', '.join(svc_titles)}")
                    if content_summary.get("faq_items"):
                        cr_parts.append(f"    FAQ: {len(content_summary['faq_items'])} frågor")
                    if content_summary.get("team_members"):
                        names = [m.get("name", "") for m in content_summary["team_members"][:5]]
                        cr_parts.append(f"    Team: {', '.join(names)}")
                    if content_summary.get("headings"):
                        h_texts = [h.get("text", "") for h in content_summary["headings"][:8]]
                        cr_parts.append(f"    Rubriker: {', '.join(h_texts)}")

        # Flags
        flags = []
        if crawl_report.get("has_blog"):
            count = crawl_report.get("blog_post_count", 0)
            flags.append(f"Blogg hittad ({count} inlägg)" if count else "Blogg/nyheter hittad")
        if crawl_report.get("has_booking"):
            flags.append("Bokningssida hittad")
        if crawl_report.get("has_pricing"):
            flags.append("Prissida hittad")
        if crawl_report.get("has_portfolio"):
            flags.append("Portfolio/referenssida hittad")
        if flags:
            cr_parts.append(f"\nSajt-egenskaper: {', '.join(flags)}")

        # Generation notes
        gen_notes = crawl_report.get("generation_notes", [])
        if gen_notes:
            cr_parts.append("\nGENERERINGSNOTER (baserat på crawl-analys):")
            for note in gen_notes:
                cr_parts.append(f"  • {note}")

        if cr_parts:
            crawl_report_section = (
                "\n═══════════════════════════════════════\n"
                "MULTI-PAGE CRAWL — ANALYS AV HELA SAJTEN\n"
                "═══════════════════════════════════════\n"
                + "\n".join(cr_parts)
            )

    # --- Social links ---
    social_str = "Inga"
    if social_links:
        social_str = ", ".join(f"{k}: {v}" for k, v in social_links.items())

    user_prompt = USER_PROMPT_TEMPLATE.format(
        business_name=_sanitize_for_prompt(business_name, 200) if business_name else "Okänt företag",
        industry=_sanitize_for_prompt(industry, 100) if industry else "Okänd",
        website_url=website_url,
        email=_sanitize_for_prompt(email, 200) if email else "Ej hittad",
        phone=_sanitize_for_prompt(phone, 50) if phone else "Ej hittad",
        address=_sanitize_for_prompt(address, 300) if address else "Ej hittad",
        social_links=social_str,
        page_title=page_title or "Ej hittad",
        hero_text=hero_text or "Ej hittad",
        hero_subtitle=hero_subtitle or "Ej hittad",
        meta_description=meta_description or "Ej hittad",
        about_text=about_text,
        headings_summary=headings_summary,
        paragraphs_summary=paragraphs_summary,
        services_summary=services_summary,
        features_summary=features_summary,
        faq_summary=faq_summary,
        team_summary=team_summary,
        css_colors=css_colors,
        visual_colors_section=visual_colors_section,
        images_summary=images_summary,
        visual_analysis_summary=visual_analysis_summary,
        crawl_report_section=crawl_report_section,
        industry_hint=industry_hint,
        recommended_sections=recommended_sections,
        logo_url=logo_url or "",
    )

    return SYSTEM_PROMPT, user_prompt
