"""
Prompt templates for AI site generation.

Flat schema — the AI fills top-level content blocks.
Navigation, footer, and page structure are auto-generated by the viewer.
"""

from __future__ import annotations

INDUSTRY_HINTS: dict[str, str] = {
    "bygg": "Fokusera på pålitlighet, erfarenhet och kvalitet. Använd starka CTA:er som 'Begär offert'. Visa upp projekt/referenser. Lyft fram certifieringar.",
    "restaurang": "Framhäv meny, atmosfär och läge. Inkludera öppettider och boknings-CTA. Visa matbilder i galleriet.",
    "frisör": "Visa upp tjänster med priser. Boka-tid-CTA. Lyxig känsla. Visa före/efter-bilder.",
    "tandvård": "Professionellt och tryggt. Framhäv behandlingar och personal. Boka-tid-CTA. Teamsektion med tandläkare.",
    "redovisning": "Seriöst och kompetent. Framhäv tjänster, erfarenhet och kundrelationer. Processektion.",
    "städ": "Pålitlighet och flexibilitet. Visa tjänster, priser och kundomdömen. Processektion.",
    "el": "Certifiering och säkerhet. Visa tjänster och tillgänglighet. Akut-CTA. Lyft auktoriserad elektriker.",
    "vvs": "Snabb service och pålitlighet. Jour-CTA. Visa tjänster tydligt. Processektion.",
    "skönhet": "Lyxig och elegant känsla. Visa produkter/behandlingar i galleri. Boka-tid-CTA.",
    "fitness": "Energisk och motiverande. Visa träningsformer, schema och priser. Boka-provpass-CTA.",
    "juridik": "Professionellt och tryggt. Framhäv expertområden och erfarenhet. Boka-konsultation-CTA.",
    "it": "Modern och teknisk. Visa tjänster, teknikstack och case studies. Boka-demo-CTA.",
}

SYSTEM_PROMPT = """Du är en expert webbdesigner som skapar moderna, vackra hemsidor för svenska småföretag.

Du får scrapad data och screenshots från ett företags befintliga hemsida. Du ska generera ett KOMPLETT och RIKT JSON-schema för en ny, professionell hemsida.

REGLER:
1. Svara ENBART med valid JSON som matchar det angivna schemat. Ingen annan text.
2. Alla texter ska vara på svenska om inte originalet är på engelska.
3. Skriv engagerande, professionella texter — ALDRIG generiska platshållare som "Lorem ipsum" eller "Vi erbjuder professionella tjänster".
4. FÄRGER: Använd de EXAKTA färgerna från den visuella analysen. Om visuell analys saknas, använd CSS-färgerna. Förbättra bara om färgerna är genuint dåliga.
5. Varje content-block (hero, about, services, etc.) är en separat nyckel. Sätt till null om sektionen inte är relevant.
6. Inkludera INTE navigation, footer eller page-struktur — det genereras automatiskt.
7. Fyll i ALLA relevanta sektioner — hero, about, features, stats, services, process, gallery, team, testimonials, faq, cta, contact.
7b. Inkludera en "section_order"-nyckel med en lista av sektionsnamn i optimal visningsordning, t.ex. ["hero", "about", "services", "features", "stats", "process", "testimonials", "team", "gallery", "faq", "cta", "contact"]. Anpassa ordningen efter bransch — t.ex. för en restaurang bör galleriet komma tidigt.
8. CTA-knappar ska ha href satt till "#contact".
9. Generera MINST 6-8 services om företaget har tjänster.
10. Generera 4-6 features/fördelar.
11. Generera 3-5 stats/nyckeltal med realistiska värden.
12. Generera 4-6 FAQ-frågor relevanta för branschen.
13. Generera 3-5 steg i en process-sektion om relevant.
14. Generera 2-4 testimonials med realistiska svenska namn.
15. Skriv LÅNGA, meningsfulla texter — about-texten ska vara minst 150 ord.
16. SEO: Generera BARA title och description i meta. Skippa structured_data och robots — det genereras automatiskt senare.
17. Använd BARA bild-URL:er som finns i listan med tillgängliga bilder. Hitta INTE PÅ nya URL:er.
18. STYLE VARIANT: Sidan tilldelas automatiskt en slumpmässig visuell stilvariant (style_variant) EFTER din generering — du behöver INTE ange den. Men var medveten om att dina sektioner kommer renderas i en av dessa varianter:

TILLGÄNGLIGA STILVARIANTER:
─────────────────────────────
Variant 0 — Original:
  Den ursprungliga designen. Rundade kort (rounded-2xl) med tunna borders, centrerade rubriker, dekorativa gradient-blobbar i bakgrunden, vertikal timeline för process-steg, accordion-FAQ. Bild till höger i om-oss. Klassiska teamkort med foto.

Variant 1 — Modern Cards:
  Moderna kort med mjuka skuggor (rounded-xl). 2-kolumnig layout, kort-baserad process istället för timeline, citat-stil testimonials med vänster-border, featured galleri där första bilden är stor. Kontaktformulär i kort-wrapper.

Variant 2 — Clean & Minimal:
  Ren och minimalistisk. Vänsterjusterade rubriker, inga dekorativa blobbar, liten border-radius (rounded-lg), FAQ visas i två kolumner utan accordion, horisontella teamkort med liten bild + text bredvid varandra. Split CTA med text vänster + knapp höger. Tvåkolumns kontaktlayout.

Variant 3 — Bold & Filled:
  Djärv och fyllig. Inga borders alls — bara stora skuggor (shadow-lg). Extra stor border-radius (rounded-3xl), pill-formade knappar (rounded-full), horisontella process-steg med anslutningslinje, masonry-stil galleri med varierande höjder, cirkulära teambilder, minimal CTA med glasmorfism-knapp.
─────────────────────────────
Anpassa ditt innehåll så att det fungerar bra oavsett variant. Skriv t.ex. tillräckligt med process-steg (3-5) för att horisontell layout ska se bra ut, och tillräckligt med FAQ (4-6) för att tvåkolumns-layout ska fyllas."""

USER_PROMPT_TEMPLATE = """Skapa en komplett, rik hemsida i JSON-format för detta företag.

═══════════════════════════════════════
FÖRETAGSINFO
═══════════════════════════════════════
Namn: {business_name}
Bransch: {industry}
Hemsida: {website_url}

KONTAKTUPPGIFTER:
Email: {email}
Telefon: {phone}
Adress: {address}
Sociala medier: {social_links}

═══════════════════════════════════════
SCRAPAD DATA FRÅN BEFINTLIG HEMSIDA
═══════════════════════════════════════

SIDTITEL: {page_title}

HERO-RUBRIK: {hero_text}
HERO-UNDERTEXT: {hero_subtitle}

META-BESKRIVNING: {meta_description}

OM OSS-TEXT:
{about_text}

ALLA RUBRIKER PÅ SIDAN:
{headings_summary}

ALLA TEXTER/STYCKEN:
{paragraphs_summary}

TJÄNSTER HITTADE:
{services_summary}

FEATURES/FÖRDELAR HITTADE:
{features_summary}

FAQ HITTADE:
{faq_summary}

TEAMMEDLEMMAR HITTADE:
{team_summary}

═══════════════════════════════════════
FÄRGER
═══════════════════════════════════════
CSS-extraherade färger: {css_colors}

{visual_colors_section}

INSTRUKTION: Om visuella färger finns ovan, ANVÄND DEM — de är exakta hex-koder från screenshots.
Om de saknas, använd CSS-färgerna som grund.

═══════════════════════════════════════
BILDER (använd ENBART dessa URL:er)
═══════════════════════════════════════
{images_summary}

═══════════════════════════════════════
VISUELL ANALYS AV BEFINTLIG HEMSIDA
═══════════════════════════════════════
{visual_analysis_summary}

{industry_hint}

═══════════════════════════════════════
JSON-SCHEMA ATT FYLLA I
═══════════════════════════════════════

VIKTIGT:
- Svara med ENBART valid JSON
- Använd de tillhandahållna bild-URL:erna. Hitta INTE PÅ nya.
- Inkludera INTE "navigation", "footer" eller "pages"
- Fyll i ALLA sektioner som är relevanta (minst 8-10 av de nedan)
- Skriv LÅNGA och DETALJERADE texter — inte korta platshållare
- features.items ska ha minst 4-6 objekt
- services.items ska ha minst 6-8 objekt
- faq.items ska ha minst 4-6 objekt
- testimonials.items ska ha minst 3-4 objekt
- stats.items ska ha 3-5 objekt

{{
  "meta": {{
    "title": "Företagsnamn | Kort beskrivning",
    "description": "150-160 tecken lång SEO-beskrivning",
    "keywords": ["nyckelord1", "nyckelord2", "..."],
    "language": "sv"
  }},
  "theme": "modern",
  "branding": {{
    "logo_url": "{logo_url}",
    "colors": {{
      "primary": "#hex",
      "secondary": "#hex",
      "accent": "#hex",
      "background": "#hex",
      "text": "#hex"
    }},
    "fonts": {{ "heading": "Inter", "body": "Inter" }}
  }},
  "business": {{
    "name": "", "tagline": "Kort slogan 5-10 ord",
    "email": "", "phone": "", "address": "",
    "org_number": null,
    "social_links": {{}}
  }},
  "hero": {{
    "headline": "Kraftfull rubrik som fångar besökaren, max 8-10 ord",
    "subtitle": "2-3 meningar som förklarar vad företaget gör och varför besökaren ska stanna",
    "cta": {{ "label": "Tydlig CTA-text", "href": "#contact" }},
    "background_image": null
  }},
  "about": {{
    "title": "Om oss",
    "text": "MINST 150 ord lång text om företaget, dess historia, värderingar och vad som gör dem unika. Beskriv deras erfarenhet, specialisering och varför kunder väljer dem.",
    "image": null,
    "highlights": [
      {{ "label": "Beskrivning", "value": "Nyckeltal" }},
      {{ "label": "Beskrivning", "value": "Nyckeltal" }},
      {{ "label": "Beskrivning", "value": "Nyckeltal" }},
      {{ "label": "Beskrivning", "value": "Nyckeltal" }}
    ]
  }},
  "features": {{
    "title": "Varför välja oss",
    "subtitle": "Kort beskrivning",
    "items": [
      {{ "title": "Fördel 1", "description": "2-3 meningar om denna fördel" }},
      {{ "title": "Fördel 2", "description": "2-3 meningar" }},
      {{ "title": "Fördel 3", "description": "2-3 meningar" }},
      {{ "title": "Fördel 4", "description": "2-3 meningar" }},
      {{ "title": "Fördel 5", "description": "2-3 meningar" }},
      {{ "title": "Fördel 6", "description": "2-3 meningar" }}
    ]
  }},
  "stats": {{
    "title": "",
    "items": [
      {{ "value": "500+", "label": "Nöjda kunder" }},
      {{ "value": "15+", "label": "Års erfarenhet" }},
      {{ "value": "98%", "label": "Kundnöjdhet" }},
      {{ "value": "24/7", "label": "Support" }}
    ]
  }},
  "services": {{
    "title": "Våra tjänster",
    "subtitle": "Kort intro",
    "items": [
      {{ "title": "Tjänst 1", "description": "2-3 meningar om tjänsten och vad den inkluderar" }},
      {{ "title": "Tjänst 2", "description": "2-3 meningar" }}
    ]
  }},
  "process": {{
    "title": "Så fungerar det",
    "subtitle": "Kort intro till processen",
    "steps": [
      {{ "title": "Steg 1", "description": "Beskrivning av steget", "step_number": 1 }},
      {{ "title": "Steg 2", "description": "Beskrivning", "step_number": 2 }},
      {{ "title": "Steg 3", "description": "Beskrivning", "step_number": 3 }}
    ]
  }},
  "gallery": {{
    "title": "Våra projekt",
    "subtitle": "Kort intro",
    "images": [
      {{ "url": "bild-url-från-listan", "alt": "Beskrivande alt-text", "caption": "Kort bildtext" }}
    ]
  }},
  "team": {{
    "title": "Möt teamet",
    "subtitle": "Kort intro",
    "members": [
      {{ "name": "Namn", "role": "Roll", "image": null, "bio": "1-2 meningar om personen" }}
    ]
  }},
  "testimonials": {{
    "title": "Vad våra kunder säger",
    "subtitle": "",
    "items": [
      {{ "text": "3-4 meningar lång recension", "author": "Svenskt namn", "role": "Kund sedan 2022" }},
      {{ "text": "3-4 meningar", "author": "Svenskt namn", "role": "Företagskund" }}
    ]
  }},
  "faq": {{
    "title": "Vanliga frågor",
    "subtitle": "",
    "items": [
      {{ "question": "Relevant fråga?", "answer": "2-3 meningar svar" }},
      {{ "question": "Relevant fråga?", "answer": "2-3 meningar svar" }}
    ]
  }},
  "cta": {{
    "title": "Redo att komma igång?",
    "text": "1-2 meningar som motiverar besökaren",
    "button": {{ "label": "CTA-text", "href": "#contact" }}
  }},
  "contact": {{
    "title": "Kontakta oss",
    "text": "1-2 meningar om hur besökaren kan nå företaget"
  }},
  "seo": {{
    "structured_data": {{}},
    "robots": "index, follow"
  }}
}}"""


def _sanitize_for_prompt(text: str, max_length: int = 500) -> str:
    """Sanitize user input before inserting into LLM prompts."""
    if not text:
        return ""
    text = text.replace("```", "")
    text = text.replace("SYSTEM:", "")
    text = text.replace("ASSISTANT:", "")
    text = text.replace("USER:", "")
    text = text.replace("HUMAN:", "")
    return text[:max_length].strip()


def build_prompt(
    business_name: str,
    industry: str | None,
    website_url: str,
    email: str | None,
    phone: str | None,
    address: str | None,
    texts: dict | None,
    colors: dict | None,
    services: list | None,
    logo_url: str | None,
    social_links: dict | None,
    images: list | None = None,
    visual_analysis: dict | None = None,
) -> tuple[str, str]:
    """Build (system_prompt, user_prompt) pair."""

    # --- Texts ---
    page_title = ""
    hero_text = ""
    hero_subtitle = ""
    meta_description = ""
    about_text = "Ingen about-text hittad."
    headings_summary = "Inga rubriker hittade."
    paragraphs_summary = "Inga texter hittade."
    features_summary = "Inga features hittade."
    faq_summary = "Ingen FAQ hittad."
    team_summary = "Inga teammedlemmar hittade."

    if texts:
        if texts.get("title"):
            page_title = _sanitize_for_prompt(texts["title"], 300)
        if texts.get("hero_text"):
            hero_text = _sanitize_for_prompt(texts["hero_text"], 300)
        if texts.get("hero_subtitle"):
            hero_subtitle = _sanitize_for_prompt(texts["hero_subtitle"], 500)
        if texts.get("description"):
            meta_description = _sanitize_for_prompt(texts["description"], 500)
        if texts.get("about"):
            about_text = _sanitize_for_prompt(texts["about"], 2000)

        # All headings
        if texts.get("headings"):
            h_parts = []
            for h in texts["headings"][:20]:
                h_parts.append(f"[{h['level']}] {_sanitize_for_prompt(h['text'], 200)}")
            if h_parts:
                headings_summary = "\n".join(h_parts)

        # All paragraphs — send much more text to the AI
        if texts.get("paragraphs"):
            p_parts = []
            for p in texts["paragraphs"][:20]:
                p_parts.append(f"- {_sanitize_for_prompt(p, 500)}")
            if p_parts:
                paragraphs_summary = "\n".join(p_parts)

        # Features
        if texts.get("features"):
            f_parts = []
            for f in texts["features"][:8]:
                title = _sanitize_for_prompt(f.get("title", ""), 150)
                desc = _sanitize_for_prompt(f.get("description", ""), 300)
                f_parts.append(f"- {title}: {desc}" if desc else f"- {title}")
            if f_parts:
                features_summary = "\n".join(f_parts)

        # FAQ
        if texts.get("faq_items"):
            faq_parts = []
            for fq in texts["faq_items"][:10]:
                q = _sanitize_for_prompt(fq.get("question", ""), 200)
                a = _sanitize_for_prompt(fq.get("answer", ""), 500)
                faq_parts.append(f"Q: {q}\nA: {a}")
            if faq_parts:
                faq_summary = "\n".join(faq_parts)

        # Team
        if texts.get("team_members"):
            tm_parts = []
            for tm in texts["team_members"][:8]:
                name = _sanitize_for_prompt(tm.get("name", ""), 100)
                role = _sanitize_for_prompt(tm.get("role", ""), 100)
                tm_parts.append(f"- {name} ({role})" if role else f"- {name}")
            if tm_parts:
                team_summary = "\n".join(tm_parts)

    # --- Services ---
    services_summary = "Inga tjänster hittade."
    if services:
        svc_list = []
        for s in services[:12]:
            title = _sanitize_for_prompt(s.get("title", ""), 150)
            desc = _sanitize_for_prompt(s.get("description", ""), 300)
            svc_list.append(f"- {title}: {desc}" if desc else f"- {title}")
        services_summary = "\n".join(svc_list)

    # --- Industry hint ---
    industry_hint = ""
    if industry and industry.lower() in INDUSTRY_HINTS:
        industry_hint = f"\n═══════════════════════════════════════\nBRANSCH-TIPS: {INDUSTRY_HINTS[industry.lower()]}\n═══════════════════════════════════════"

    # --- Colors ---
    css_colors = "Inga färger"
    if colors:
        css_colors = f"Primary: {colors.get('primary', '?')}, Secondary: {colors.get('secondary', '?')}, Accent: {colors.get('accent', '?')}"

    # Visual colors (from vision analysis — these are the REAL colors)
    visual_colors_section = ""
    if visual_analysis and isinstance(visual_analysis.get("colors"), dict):
        vc = visual_analysis["colors"]
        parts = ["VISUELLA FÄRGER (exakta hex-koder från screenshots — ANVÄND DESSA):"]
        for key in ["primary", "secondary", "accent", "background", "text"]:
            if vc.get(key):
                parts.append(f"  {key}: {vc[key]}")
        visual_colors_section = "\n".join(parts)

    # --- Images ---
    images_summary = "Inga bilder tillgängliga."
    if images:
        img_parts = []
        for img in images[:20]:
            url = img.get("url", "")
            alt = img.get("alt", "")
            cat = img.get("category", "general")
            w = img.get("width", "?")
            h = img.get("height", "?")
            if url:
                line = f"- [{cat}] {url}"
                if alt:
                    line += f" (alt: {alt})"
                if w != "?" and h != "?":
                    line += f" [{w}x{h}]"
                img_parts.append(line)
        if img_parts:
            images_summary = "\n".join(img_parts)

    # --- Visual analysis summary ---
    visual_analysis_summary = "Ingen visuell analys tillgänglig."
    if visual_analysis:
        va_parts = []

        if visual_analysis.get("design_style"):
            va_parts.append(f"Designstil: {visual_analysis['design_style']}")
        if visual_analysis.get("mood"):
            va_parts.append(f"Känsla/stämning: {visual_analysis['mood']}")
        if visual_analysis.get("overall_quality"):
            va_parts.append(f"Kvalitetsnivå: {visual_analysis['overall_quality']}")

        if visual_analysis.get("typography"):
            typo = visual_analysis["typography"]
            va_parts.append(f"Typografi: {typo.get('heading_style', '?')} rubriker, {typo.get('body_style', '?')} brödtext, vikt: {typo.get('heading_weight', '?')}")

        if visual_analysis.get("layout"):
            layout = visual_analysis["layout"]
            va_parts.append(f"Layout: hero={layout.get('hero_type', '?')}, sektioner={layout.get('section_count', '?')}")

        if visual_analysis.get("content_sections"):
            va_parts.append("Identifierade sektioner:")
            for sec in visual_analysis["content_sections"][:10]:
                sec_type = sec.get("type", "?")
                headline = sec.get("headline", "")
                summary = sec.get("summary", "")
                va_parts.append(f"  - [{sec_type}] {headline}: {summary}" if headline else f"  - [{sec_type}] {summary}")

        if visual_analysis.get("cta_buttons"):
            va_parts.append(f"CTA-knappar: {', '.join(visual_analysis['cta_buttons'][:5])}")

        if visual_analysis.get("business_info_visible"):
            biz = visual_analysis["business_info_visible"]
            for key in ["name", "tagline", "phone", "email"]:
                if biz.get(key):
                    va_parts.append(f"Synlig {key}: {biz[key]}")

        if visual_analysis.get("images"):
            img_info = visual_analysis["images"]
            va_parts.append(f"Bilder: {img_info.get('total_visible', '?')} synliga, stil={img_info.get('image_style', '?')}, kvalitet={img_info.get('image_quality', '?')}")

        if visual_analysis.get("improvement_areas"):
            areas = visual_analysis["improvement_areas"]
            if isinstance(areas, list):
                va_parts.append(f"Förbättringsområden: {', '.join(areas[:4])}")
            else:
                va_parts.append(f"Förbättringsområden: {areas}")

        if va_parts:
            visual_analysis_summary = "\n".join(va_parts)

    # --- Social links ---
    social_str = "Inga"
    if social_links:
        social_str = ", ".join(f"{k}: {v}" for k, v in social_links.items())

    user_prompt = USER_PROMPT_TEMPLATE.format(
        business_name=_sanitize_for_prompt(business_name, 200) if business_name else "Okänt företag",
        industry=_sanitize_for_prompt(industry, 100) if industry else "Okänd",
        website_url=website_url,
        email=_sanitize_for_prompt(email, 200) if email else "Ej hittad",
        phone=_sanitize_for_prompt(phone, 50) if phone else "Ej hittad",
        address=_sanitize_for_prompt(address, 300) if address else "Ej hittad",
        social_links=social_str,
        page_title=page_title or "Ej hittad",
        hero_text=hero_text or "Ej hittad",
        hero_subtitle=hero_subtitle or "Ej hittad",
        meta_description=meta_description or "Ej hittad",
        about_text=about_text,
        headings_summary=headings_summary,
        paragraphs_summary=paragraphs_summary,
        services_summary=services_summary,
        features_summary=features_summary,
        faq_summary=faq_summary,
        team_summary=team_summary,
        css_colors=css_colors,
        visual_colors_section=visual_colors_section,
        images_summary=images_summary,
        visual_analysis_summary=visual_analysis_summary,
        industry_hint=industry_hint,
        logo_url=logo_url or "",
    )

    return SYSTEM_PROMPT, user_prompt
